/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type JsQueryEngine = QueryEngine
export class QueryEngine {
  constructor(callback: (...args: any[]) => any)
  call(): void
}
